### PR TITLE
Fix typo in  documentation

### PR DESCRIPTION
**Pull request by r3mcos3**
fix for typo "gain" instead of again

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Review by sinclairpaul — COMMENTED** [review]
This isn't correct though is it, the sentence is "Of course, if you'd really want to, you could also use this add-on to gain access to your Home Assistant configuration via FTP."  i.e. you can use the addon to get access to your config

**Comment by tjorim** [comment]
This fix seems correct to me, you 'gain access'.

**Review by tjorim — APPROVED** [review]

**Comment by sinclairpaul** [comment]
Yep, my bad, I read it backwards!

**Review by frenck — APPROVED** [review]
Thanks, @r3mcos3 👍

**Pull request merged**
